### ISSUE TITLE
Include in REDCap-related list?

### ISSUE THREAD

**Issue by wibeasley** [tjrivera/go-cap#4]
Hi @tjrivera, I just found your golang repo through a recent post of yours. Is this production or semi-production ready? If so, I'd like to include it in a laundry list that tries to collect these things so users can choose the best tool.

If it's not ready yet, just email me, or create a PR when it is.

**Comment by tjrivera** [comment]
Hi @wibeasley I'm comfortable with you putting go-cap in the list. It isn't yet full-featured, but I am using it in production on a few projects. thanks!

**Comment by wibeasley** [comment]
Good.  Tell me if something changes, or you want to change the description.
